### PR TITLE
Created in-project maven repo for missing libs

### PR DESCRIPTION
**Pull request by matthias-mueller**

### CODE REVIEW

**Comment by nuest** [comment]
I strongly advice against this! We have a public maven repo where we can deploy such artifacts. This repository is now enlarged forever with a bad practice...

**Comment by nuest** [comment]
This goes against all the efforts spend on not having binary dependencies in this project...

**Comment by matthias-mueller** [comment]
1. Despite these efforts, the project still _has_ binary dependencies which had not been mavenized during the migration. This migration was done by the org's core team. Building the project required downloading libraries form external sources and adding them manually. An automated maven build was impossible. I fixed this since project with included binaries is still better than a project that won't build.
2. Artifact deployment on the org's maven server is beyond my permissions / abilities. Since you've spotted an opportunity for helping out here, your contribution is very much appreciated.

**Comment by matthias-mueller** [comment]
@bpross-52n : Can you please deploy the ESRI libs as maven artifacts and adjust the POMs?

**Pull request merged**
